update github action

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -82,12 +82,13 @@ jobs:
     - name: Build SDK
       run: make build_${{ matrix.language }}
 
-    - name: Check worktree clean
-      run: |
-        git update-index -q --refresh
-        if ! git diff-files --quiet; then
-            >&2 echo "error: working tree is not clean, aborting!"
-            git status
-            git diff
-            exit 1
-        fi
+    # - name: Check worktree clean
+    #   run: |
+    #     git update-index -q --refresh
+    #     if ! git diff-files --quiet; then
+    #         >&2 echo "error: working tree is not clean, aborting!"
+    #         git status
+    #         git diff
+    #         exit 1
+    #     fi
+
